name: new_backend
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  dart_jsonwebtoken: ^3.2.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqlite3: ^2.6.0
  shelf_web_socket: ^1.0.0
  youtube_explode_dart: ^2.3.10

  teledart: ^0.6.1
  dotenv: ^4.2.0
  web_socket_channel: ^2.4.0
  uuid: ^4.5.1
  crypto: ^3.0.6
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
